// Global
import type { Meta, StoryObj } from '@storybook/react';

// Lib
import { expandObj, flattenObj } from 'lib/object-parser';

// Local
import { CardItemProps, Default } from 'components/authorable/shared/hztl-page-content/CardItem';
import defaultData from './CardItem.mock-data';

const meta: Meta<typeof Default> = {
  argTypes: {
    'fields.CardImage.value.alt': {
      table: {
        category: 'fields',
      },
    },
    'fields.CardImage.value.src': {
      table: {
        category: 'fields',
      },
    },
    'fields.CardImage.value.title': {
      table: {
        category: 'fields',
      },
    },
    'fields.CardLink1.value.href': {
      table: {
        category: 'fields',
      },
    },
    'fields.CardLink1.value.linktype': {
      table: {
        category: 'fields',
      },
    },
    'fields.CardLink1.value.target': {
      table: {
        category: 'fields',
      },
    },
    'fields.CardLink1.value.text': {
      table: {
        category: 'fields',
      },
    },
    'fields.CardLink2.value.href': {
      table: {
        category: 'fields',
      },
    },
    'fields.CardLink2.value.linktype': {
      table: {
        category: 'fields',
      },
    },
    'fields.CardLink2.value.target': {
      table: {
        category: 'fields',
      },
    },
    'fields.CardLink2.value.text': {
      table: {
        category: 'fields',
      },
    },
    'fields.Description.value': {
      table: {
        category: 'fields',
      },
    },
    'fields.Eyebrow.value': {
      table: {
        category: 'fields',
      },
    },
    'fields.Heading.value': {
      table: {
        category: 'fields',
      },
    },
    'fields.Subheading.value': {
      table: {
        category: 'fields',
      },
    },
    'rendering.componentName': {
      table: {
        category: 'rendering',
      },
    },
    'rendering.dataSource': {
      table: {
        category: 'rendering',
      },
    },
    uid: {
      description:
        "A unique ID generated by Sitecore that will serve as the basis for the modal's ID attribute.",
    },
    /* eslint-disable  @typescript-eslint/no-explicit-any */
  } as any,
  component: Default,
  decorators: [
    (Story) => (
      <div className="max-w-[395px]">
        <Story />
      </div>
    ),
  ],
  parameters: {
    docs: {
      description: {
        component: `
## Overview
The Card component is a flexible container that groups related content and actions about a single subject. It often includes elements like images, text, buttons, and other interactive components, making it ideal for displaying concise, visually appealing information.

## Usage
Use the Card component to present a summarized view of content or to showcase specific information, such as a product, user profile, or news article. Cards are best suited for dashboard layouts, grid views, or when you need to display content in an organized, digestible format. Ensure that the content within the card is easy to scan and encourages interaction through clear actions or links.`,
      },
    },
  },
  title: 'Components/Authorable/shared/hztl-page-content/Card Item',
};

export default meta;

type Story = StoryObj<typeof Default>;

export const Card: Story = {
  args: {
    ...flattenObj(defaultData),
  },
  render: (args) => {
    return <Default {...(expandObj({ ...args }) as CardItemProps)} />;
  },
};
