
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { ComponentProps } from '../lib/component-props';
// @ts-ignore 
import { SiteStructure as FeatureHztlFoundationSiteStructure } from "./Feature.HztlFoundation.model"

export namespace SiteStructure.Footer {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Footer
    */
    export type Footer =  {
        fields?: { 
            /**
            * Represents the Footer Columns field (fad6beb9-19f0-40b9-99bf-8d10903192f9).
            */
            footerColumns?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Footer
    */
    export type FooterJson =  {
        
            /**
            * Represents the Footer Columns field (fad6beb9-19f0-40b9-99bf-8d10903192f9).
            */
            footerColumns?: {
                jsonValue: Item[]
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/FooterColumn
    */
    export type FooterColumn =  {
        fields?: { 
            /**
            * Represents the Column Links field (e2ba8384-6ddd-4513-82ac-abd0e087c430).
            */
            columnLinks?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/FooterColumn
    */
    export type FooterColumnJson =  {
        
            /**
            * Represents the Column Links field (e2ba8384-6ddd-4513-82ac-abd0e087c430).
            */
            columnLinks?: {
                jsonValue: Item[]
            };


    }
}
export namespace SiteStructure {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Site Structure Folder
    */
    export type SiteStructureFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Site Structure Folder
    */
    export type SiteStructureFolderJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace SiteStructure.Footer.Constants {

    export const Footer = {
        TemplateId: "39461909-13b3-4b3e-a306-2c01aa783f5e",
    
        BaseTemplateIds: [
        ]
    }
    export const FooterColumn = {
        TemplateId: "08d755a3-a6fa-4f8b-b574-414077d83a52",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace SiteStructure.Constants {

    export const SiteStructureFolder = {
        TemplateId: "7dd48aec-39d7-4ce2-810b-e82171dbe8da",
    
        BaseTemplateIds: [
        ]
    }
}    


