
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { ComponentProps } from '../lib/component-props';
// @ts-ignore 
import { HztlPageContent as FeatureHztlFoundationHztlPageContent } from "./Feature.HztlFoundation.model"
// @ts-ignore 
import { SiteStructure as FeatureHztlFoundationSiteStructure } from "./Feature.HztlFoundation.model"
// @ts-ignore 
import { HztlSiteStructure as FeatureHztlFoundationHztlSiteStructure } from "./Feature.HztlFoundation.model"

export namespace HztlPageContent {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Accordion
    */
    export type Accordion =  {
        fields?: { 
            /**
            * Represents the Text field (5151f09c-75b1-4c5b-9fdf-9f66e9743a88).
            */
            accordionList?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Accordion
    */
    export type AccordionJson =  {
        
            /**
            * Represents the Text field (5151f09c-75b1-4c5b-9fdf-9f66e9743a88).
            */
            accordionList?: {
                jsonValue: Item[]
            };


    }
}
export namespace HztlPageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Accordion
    */
    export type Accordion =  {
        fields?: { 
            /**
            * Represents the Open Multiple Accordion At Same Time field (228ce8c6-03e5-4aa6-9874-c3bd39aebcd0).
            */
            openMultipleAccordionAtSameTime?: Field<boolean>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Accordion
    */
    export type AccordionJson =  {
        
            /**
            * Represents the Open Multiple Accordion At Same Time field (228ce8c6-03e5-4aa6-9874-c3bd39aebcd0).
            */
            openMultipleAccordionAtSameTime?: {
                jsonValue: Field<boolean>
            };


    }
}
export namespace HztlPageContent {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Accordion Folder
    */
    export type AccordionFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Accordion Folder
    */
    export type AccordionFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Accordion Item
    */
    export type AccordionItem =  {
        fields?: { 
            /**
            * Represents the Content field (261f0553-7346-4ebd-bdeb-82f737716e7e).
            */
            content?: Field<string>;

            /**
            * Represents the Heading field (bc2e4823-4876-46fe-ac5a-89df86792ac5).
            */
            heading?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Accordion Item
    */
    export type AccordionItemJson =  {
        
            /**
            * Represents the Content field (261f0553-7346-4ebd-bdeb-82f737716e7e).
            */
            content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Heading field (bc2e4823-4876-46fe-ac5a-89df86792ac5).
            */
            heading?: {
                jsonValue: Field<string>
            };


    }
}
export namespace HztlPageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Breadcrumb
    */
    export type Breadcrumb =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Breadcrumb
    */
    export type BreadcrumbJson =  {
        

    }
}
export namespace HztlPageContent {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Card
    */
    export type Card =  {
        fields?: { 
            /**
            * Represents the Text field (d7b576b3-7bea-46e6-bb0a-49edb06481d7).
            */
            CardImage?: ImageField;

            /**
            * Represents the CardLink1 field (c9d402e1-0e1c-4b9b-9f72-0c66f4249145).
            */
            CardLink1?: LinkField;

            /**
            * Represents the CardLink2 field (ebf65880-3433-4f9c-82fe-33400ef39565).
            */
            CardLink2?: LinkField;

            /**
            * Represents the Description field (06cc0659-30f3-4acd-8d70-acd3b71a021e).
            */
            Description?: Field<string>;

            /**
            * Represents the Eyebrow field (2bf4e3c9-4548-48cc-90dc-bac4db7d054f).
            */
            Eyebrow?: Field<string>;

            /**
            * Represents the Heading field (e12882dc-a694-483c-a1f7-2917c96cdd5a).
            */
            Heading?: Field<string>;

            /**
            * Represents the Subheading field (dbd8adc9-d5d2-45d7-a093-a74deaf084d0).
            */
            Subheading?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Card
    */
    export type CardJson =  {
        
            /**
            * Represents the Text field (d7b576b3-7bea-46e6-bb0a-49edb06481d7).
            */
            CardImage?: {
                jsonValue: ImageField
            };

            /**
            * Represents the CardLink1 field (c9d402e1-0e1c-4b9b-9f72-0c66f4249145).
            */
            CardLink1?: {
                jsonValue: LinkField
            };

            /**
            * Represents the CardLink2 field (ebf65880-3433-4f9c-82fe-33400ef39565).
            */
            CardLink2?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Description field (06cc0659-30f3-4acd-8d70-acd3b71a021e).
            */
            Description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Eyebrow field (2bf4e3c9-4548-48cc-90dc-bac4db7d054f).
            */
            Eyebrow?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Heading field (e12882dc-a694-483c-a1f7-2917c96cdd5a).
            */
            Heading?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Subheading field (dbd8adc9-d5d2-45d7-a093-a74deaf084d0).
            */
            Subheading?: {
                jsonValue: Field<string>
            };


    }
}
export namespace HztlPageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Card
    */
    export type Card =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Card
    */
    export type CardJson =  {
        

    }
}
export namespace HztlPageContent {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Card Folder
    */
    export type CardFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Card Folder
    */
    export type CardFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/CardList
    */
    export type CardList =  {
        fields?: { 
            /**
            * Represents the CardListLink field (2f5abe69-579f-4e06-8eb4-709d8a9529bf).
            */
            CardListLink?: LinkField;

            /**
            * Represents the CardListLink2 field (d0ad9cc0-515d-4668-8e7a-1bfdae814840).
            */
            CardListLink2?: LinkField;

            /**
            * Represents the CardListTitle field (0418e27b-957b-4de8-a13f-40cac199c1e1).
            */
            CardListTitle?: Field<string>;

            /**
            * Represents the CartListText field (fb848371-e07b-4236-9601-65c30ecf4c39).
            */
            CartListText?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/CardList
    */
    export type CardListJson =  {
        
            /**
            * Represents the CardListLink field (2f5abe69-579f-4e06-8eb4-709d8a9529bf).
            */
            CardListLink?: {
                jsonValue: LinkField
            };

            /**
            * Represents the CardListLink2 field (d0ad9cc0-515d-4668-8e7a-1bfdae814840).
            */
            CardListLink2?: {
                jsonValue: LinkField
            };

            /**
            * Represents the CardListTitle field (0418e27b-957b-4de8-a13f-40cac199c1e1).
            */
            CardListTitle?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the CartListText field (fb848371-e07b-4236-9601-65c30ecf4c39).
            */
            CartListText?: {
                jsonValue: Field<string>
            };


    }
}
export namespace HztlPageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/CardList
    */
    export type CardList =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/CardList
    */
    export type CardListJson =  {
        

    }
}
export namespace HztlPageContent {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/CardList Folder
    */
    export type CardListFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/CardList Folder
    */
    export type CardListFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Carousel
    */
    export type Carousel =  {
        fields?: { 
            /**
            * Represents the Text field (b73437dd-a7cb-40fe-9ffe-f0df3d680b49).
            */
            carouselList?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Carousel
    */
    export type CarouselJson =  {
        
            /**
            * Represents the Text field (b73437dd-a7cb-40fe-9ffe-f0df3d680b49).
            */
            carouselList?: {
                jsonValue: Item[]
            };


    }
}
export namespace HztlPageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Carousel
    */
    export type Carousel =  {
        fields?: { 
            /**
            * Represents the Disable Auto Loop field (4e9699dd-7b5d-440a-97a8-16013db8994b).
            */
            disableAutoLoop?: Field<string>;

            /**
            * Represents the Disable Auto Rotation field (83103cb9-0209-4b6c-8db2-bdff6c4ff80d).
            */
            disableAutoRotation?: Field<boolean>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Carousel
    */
    export type CarouselJson =  {
        
            /**
            * Represents the Disable Auto Loop field (4e9699dd-7b5d-440a-97a8-16013db8994b).
            */
            disableAutoLoop?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Disable Auto Rotation field (83103cb9-0209-4b6c-8db2-bdff6c4ff80d).
            */
            disableAutoRotation?: {
                jsonValue: Field<boolean>
            };


    }
}
export namespace HztlPageContent {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Carousel Folder
    */
    export type CarouselFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Carousel Folder
    */
    export type CarouselFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Carousel Item
    */
    export type CarouselItem =  {
        fields?: { 
            /**
            * Represents the Description field (189b2fd9-3888-4053-adce-a294c0a76412).
            */
            description?: Field<string>;

            /**
            * Represents the Image field (148c7427-11a8-40fa-8190-1b09e0fd853b).
            */
            image?: ImageField;

            /**
            * Represents the Primary CTA field (c2af1e8d-7532-4ade-ae5b-f0708b72ef0d).
            */
            primaryCTA?: LinkField;

            /**
            * Represents the Secondary CTA field (439fa51b-a3c5-4fa0-bd3b-4114ba741349).
            */
            secondaryCTA?: LinkField;

            /**
            * Represents the Title field (3acdcafc-bd69-46e1-a32b-377d173f616c).
            */
            title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Carousel Item
    */
    export type CarouselItemJson =  {
        
            /**
            * Represents the Description field (189b2fd9-3888-4053-adce-a294c0a76412).
            */
            description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Image field (148c7427-11a8-40fa-8190-1b09e0fd853b).
            */
            image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Primary CTA field (c2af1e8d-7532-4ade-ae5b-f0708b72ef0d).
            */
            primaryCTA?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Secondary CTA field (439fa51b-a3c5-4fa0-bd3b-4114ba741349).
            */
            secondaryCTA?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Title field (3acdcafc-bd69-46e1-a32b-377d173f616c).
            */
            title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace SiteStructure.Footer {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Footer
    */
    export type Footer =  {
        fields?: { 
            /**
            * Represents the Footer Columns field (fad6beb9-19f0-40b9-99bf-8d10903192f9).
            */
            footerColumns?: Item[];

            /**
            * Represents the Footer Logo field (ee79b5c7-4f16-41e9-9db3-91df531562fd).
            */
            footerLogo?: ImageField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Footer
    */
    export type FooterJson =  {
        
            /**
            * Represents the Footer Columns field (fad6beb9-19f0-40b9-99bf-8d10903192f9).
            */
            footerColumns?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Footer Logo field (ee79b5c7-4f16-41e9-9db3-91df531562fd).
            */
            footerLogo?: {
                jsonValue: ImageField
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/FooterColumn
    */
    export type FooterColumn =  {
        fields?: { 
            /**
            * Represents the Column Links field (e2ba8384-6ddd-4513-82ac-abd0e087c430).
            */
            columnLinks?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/FooterColumn
    */
    export type FooterColumnJson =  {
        
            /**
            * Represents the Column Links field (e2ba8384-6ddd-4513-82ac-abd0e087c430).
            */
            columnLinks?: {
                jsonValue: Item[]
            };


    }
}
export namespace HztlPageContent {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Hero
    */
    export type Hero =  {
        fields?: { 
            /**
            * Represents the Text 3 field (72c8e421-0bdd-46ff-a012-3835f6e52060).
            */
            Description?: Field<string>;

            /**
            * Represents the Text field (05be0e84-140d-4d03-9b12-8c4a9dc2a25b).
            */
            Heading?: Field<string>;

            /**
            * Represents the __Standard Werte field (828b4c29-c92b-420f-8173-be73559bb31b).
            */
            Image?: ImageField;

            /**
            * Represents the Link field (ad30fb20-9a56-4367-af5b-7c733770a9e2).
            */
            Link1?: LinkField;

            /**
            * Represents the Link field (1905ebfb-2e4f-4eb7-8a6d-2ac9f436c03d).
            */
            Link2?: LinkField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Hero
    */
    export type HeroJson =  {
        
            /**
            * Represents the Text 3 field (72c8e421-0bdd-46ff-a012-3835f6e52060).
            */
            Description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text field (05be0e84-140d-4d03-9b12-8c4a9dc2a25b).
            */
            Heading?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the __Standard Werte field (828b4c29-c92b-420f-8173-be73559bb31b).
            */
            Image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Link field (ad30fb20-9a56-4367-af5b-7c733770a9e2).
            */
            Link1?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Link field (1905ebfb-2e4f-4eb7-8a6d-2ac9f436c03d).
            */
            Link2?: {
                jsonValue: LinkField
            };


    }
}
export namespace HztlPageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Hero
    */
    export type Hero =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Hero
    */
    export type HeroJson =  {
        

    }
}
export namespace HztlPageContent {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Hero Folder
    */
    export type HeroFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Hero Folder
    */
    export type HeroFolderJson =  {
        

    }
}
export namespace HztlSiteStructure.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Hztl Site Structure/Rendering Parameters/Main Layout
    */
    export type MainLayout =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Hztl Site Structure/Rendering Parameters/Main Layout
    */
    export type MainLayoutJson =  {
        

    }
}
export namespace SiteStructure {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Site Structure Folder
    */
    export type SiteStructureFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Site Structure Folder
    */
    export type SiteStructureFolderJson =  {
        

    }
}
export namespace SiteStructure.Footer {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Social Media
    */
    export type SocialMedia =  {
        fields?: { 
            /**
            * Represents the Social Links field (232c2560-a480-46a8-bd23-dbcb38d2aedc).
            */
            socialMediaLinks?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Social Media
    */
    export type SocialMediaJson =  {
        
            /**
            * Represents the Social Links field (232c2560-a480-46a8-bd23-dbcb38d2aedc).
            */
            socialMediaLinks?: {
                jsonValue: Item[]
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Social Media Item
    */
    export type SocialMediaItem =  {
        fields?: { 
            /**
            * Represents the Social Media Link field (889296b7-cee2-4b50-b648-99c604288152).
            */
            socialMediaLink?: LinkField;

            /**
            * Represents the Social Media Logo field (5648e0e7-f035-48f5-aebe-296b8a096192).
            */
            socialMediaLogo?: ImageField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Social Media Item
    */
    export type SocialMediaItemJson =  {
        
            /**
            * Represents the Social Media Link field (889296b7-cee2-4b50-b648-99c604288152).
            */
            socialMediaLink?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Social Media Logo field (5648e0e7-f035-48f5-aebe-296b8a096192).
            */
            socialMediaLogo?: {
                jsonValue: ImageField
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace HztlPageContent.Constants {

    export const Accordion = {
        TemplateId: "2c50e47d-31a4-4fff-85ff-eff1fb1f8038",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HztlPageContent.RenderingParameters.Constants {

    export const Accordion = {
        TemplateId: "7a436cb9-473e-4270-99b3-d301964d7689",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HztlPageContent.Constants {

    export const AccordionFolder = {
        TemplateId: "d27b8710-9ec7-4b87-adf1-b117a8a45d2f",
    
        BaseTemplateIds: [
        ]
    }
    export const AccordionItem = {
        TemplateId: "17df4652-d9f8-4916-b09e-fc809a260891",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HztlPageContent.RenderingParameters.Constants {

    export const Breadcrumb = {
        TemplateId: "621becbf-9a12-4a10-ba04-b2a0ecd6ca91",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HztlPageContent.Constants {

    export const Card = {
        TemplateId: "3a7d27e5-b935-46da-b8fb-fe1e260957d8",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HztlPageContent.RenderingParameters.Constants {

    export const Card = {
        TemplateId: "c3ed0731-9d2b-4ec8-9494-760921cadd37",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HztlPageContent.Constants {

    export const CardFolder = {
        TemplateId: "315c2094-ebe1-45d3-b7f6-c57fec3d057c",
    
        BaseTemplateIds: [
        ]
    }
    export const CardList = {
        TemplateId: "15666f04-9b31-48a4-be10-89485b9a553d",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HztlPageContent.RenderingParameters.Constants {

    export const CardList = {
        TemplateId: "49561e14-e1dd-4b06-b8e0-beaf908016c7",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HztlPageContent.Constants {

    export const CardListFolder = {
        TemplateId: "ba4df361-c4c6-4045-bc3d-608266e63182",
    
        BaseTemplateIds: [
        ]
    }
    export const Carousel = {
        TemplateId: "7d645e35-f14b-4ad7-872a-5c706b070cfd",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HztlPageContent.RenderingParameters.Constants {

    export const Carousel = {
        TemplateId: "f90e159f-b6d9-4e53-8819-270bb018ee39",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HztlPageContent.Constants {

    export const CarouselFolder = {
        TemplateId: "0cd3b2a0-be95-41bd-85c8-d79110ce5dbf",
    
        BaseTemplateIds: [
        ]
    }
    export const CarouselItem = {
        TemplateId: "7a137b26-5e9c-4cbb-8731-54b3b6593a4d",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace SiteStructure.Footer.Constants {

    export const Footer = {
        TemplateId: "39461909-13b3-4b3e-a306-2c01aa783f5e",
    
        BaseTemplateIds: [
        ]
    }
    export const FooterColumn = {
        TemplateId: "08d755a3-a6fa-4f8b-b574-414077d83a52",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HztlPageContent.Constants {

    export const Hero = {
        TemplateId: "4bda55f9-dbec-4f86-85fe-e42132b4dee6",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HztlPageContent.RenderingParameters.Constants {

    export const Hero = {
        TemplateId: "e49ce774-5c1d-4727-9796-a256da64893a",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HztlPageContent.Constants {

    export const HeroFolder = {
        TemplateId: "fcd9b72d-9922-426f-a0de-9546d030279d",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace HztlSiteStructure.RenderingParameters.Constants {

    export const MainLayout = {
        TemplateId: "6413fe87-e29d-4ee6-a4ef-d1a5c659a2b1",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace SiteStructure.Constants {

    export const SiteStructureFolder = {
        TemplateId: "7dd48aec-39d7-4ce2-810b-e82171dbe8da",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace SiteStructure.Footer.Constants {

    export const SocialMedia = {
        TemplateId: "b05f1a98-eec9-4c0b-b29a-e4d1235f06d8",
    
        BaseTemplateIds: [
        ]
    }
    export const SocialMediaItem = {
        TemplateId: "5e1ae8e0-8f0c-443c-ac85-144f1e47e4af",
    
        BaseTemplateIds: [
        ]
    }
}    


