
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { ComponentProps } from '../lib/component-props';
// @ts-ignore 
import { Data as FoundationHztlFoundationData } from "./Foundation.HztlFoundation.model"

export namespace Data.Links {

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Data/Links/Generic Link
    */
    export type GenericLink =  {
        fields?: { 
            /**
            * Represents the Link field (1e5322d4-6c42-466f-ad23-32a4c7aeacc3).
            */
            link?: LinkField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/HztlFoundation/Data/Links/Generic Link
    */
    export type GenericLinkJson =  {
        
            /**
            * Represents the Link field (1e5322d4-6c42-466f-ad23-32a4c7aeacc3).
            */
            link?: {
                jsonValue: LinkField
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Data.Links.Constants {

    export const GenericLink = {
        TemplateId: "b7e9466d-8242-4efc-a137-c21c9e181ecb",
    
        BaseTemplateIds: [
        ]
    }
}    


