
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { ComponentProps } from '../lib/component-props';
// @ts-ignore 
import { Project as ProjectHztlFoundationProject } from "./Project.HztlFoundation.model"

export namespace Project.HztlFoundation {

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Headless Site
    */
    export type HeadlessSite =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Headless Site
    */
    export type HeadlessSiteJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Headless Tenant
    */
    export type HeadlessTenant =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Headless Tenant
    */
    export type HeadlessTenantJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/JSS Settings
    */
    export type JssSettings =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/JSS Settings
    */
    export type JssSettingsJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page
    */
    export type Page =  {
        fields?: { 
            /**
            * Represents the Content field (2ec2526b-52e4-469d-83a7-401d7b50ae1b).
            */
            Content?: Field<string>;

            /**
            * Represents the Title field (9c063550-df49-46a3-99c6-f830a981a018).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Page
    */
    export type PageJson =  {
        
            /**
            * Represents the Content field (2ec2526b-52e4-469d-83a7-401d7b50ae1b).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (9c063550-df49-46a3-99c6-f830a981a018).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Design Folder
    */
    export type PageDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Page Design Folder
    */
    export type PageDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Designs
    */
    export type PageDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Page Designs
    */
    export type PageDesignsJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Partial Design Folder
    */
    export type PartialDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Partial Design Folder
    */
    export type PartialDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Partial Designs
    */
    export type PartialDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Partial Designs
    */
    export type PartialDesignsJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Project.HztlFoundation.Constants {

    export const HeadlessSite = {
        TemplateId: "ac5c5911-839e-4130-8675-5d77b750cb58",
    
        BaseTemplateIds: [
        ]
    }
    export const HeadlessTenant = {
        TemplateId: "c3ad7833-764b-4de0-b42f-dafcdc6a93ef",
    
        BaseTemplateIds: [
        ]
    }
    export const JssSettings = {
        TemplateId: "6d778a82-f230-42f7-9ebb-0c25ebc4a6cc",
    
        BaseTemplateIds: [
        ]
    }
    export const Page = {
        TemplateId: "b936184f-fca2-4acc-b7ed-b9f4e6170b8c",
    
        BaseTemplateIds: [
        ]
    }
    export const PageDesignFolder = {
        TemplateId: "9c75cc3a-b79b-47e2-a801-40c6f7414c6f",
    
        BaseTemplateIds: [
        ]
    }
    export const PageDesigns = {
        TemplateId: "11d22431-f378-4a68-8ee5-ffc1ea5005cf",
    
        BaseTemplateIds: [
        ]
    }
    export const PartialDesignFolder = {
        TemplateId: "e2f40205-f385-4134-a57f-bab1f3850e2f",
    
        BaseTemplateIds: [
        ]
    }
    export const PartialDesigns = {
        TemplateId: "f004e782-2325-407d-aa8f-f3195808f8ac",
    
        BaseTemplateIds: [
        ]
    }
}    


