---
ID: "e7c646db-673b-43c3-b428-150c0d2c8e25"
Parent: "1f14ced2-7051-4f4e-9f2c-6a06d28f72f9"
Template: "1f14ced2-7051-4f4e-9f2c-6a06d28f72f9"
Path: /sitecore/templates/Feature/HztlFoundation/Global Data/Global Folder/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240617T130032Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dhruvi.patel@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dhruvi.patel@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "36d734ae-cf56-4a12-b3d3-dd7a186f2524"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dhruvi.patel@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240617T130032Z
