---
ID: "b192372f-4dfd-4938-816f-99feff5c0e28"
Parent: "49561e14-e1dd-4b06-b8e0-beaf908016c7"
Template: "49561e14-e1dd-4b06-b8e0-beaf908016c7"
Path: /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/CardList/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6945f3da-e94c-48f7-a552-81ae46a6b9a0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\pbarron@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240312T162813Z
