---
ID: "a3884a5c-4ceb-4c63-b3b5-8dfac8cae84f"
Parent: "621becbf-9a12-4a10-ba04-b2a0ecd6ca91"
Template: "621becbf-9a12-4a10-ba04-b2a0ecd6ca91"
Path: /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Breadcrumb/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fcacac02-67f1-4a75-95aa-3e8b9ffd5c82"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\asavalagi@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240531T123657Z
