---
ID: "2194df1d-3375-427e-a9db-2e3618b244c7"
Parent: "e58d4e11-a20d-4c45-9205-fd3e9edcdba8"
Template: "e58d4e11-a20d-4c45-9205-fd3e9edcdba8"
Path: /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/CustomForm/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "57afb50a-79ee-4661-b820-fc6957a8e015"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\asavalagi@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240620T134529Z
