---
ID: "2b3ad18b-3689-4090-8c2f-1c3d2ed9d3a6"
Parent: "f90e159f-b6d9-4e53-8819-270bb018ee39"
Template: "f90e159f-b6d9-4e53-8819-270bb018ee39"
Path: /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Carousel/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4ced856d-1294-40e9-9391-efff9497b298"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\asavalagi@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240612T122603Z
