---
ID: "4d773532-73f6-4ce1-8761-79394380ebb1"
Parent: "5148d5b4-8fbd-4f02-a7aa-403c6827d92c"
Template: "5148d5b4-8fbd-4f02-a7aa-403c6827d92c"
Path: /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Article/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6435b763-043b-41e8-97c2-2a96e48fefd1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arawat@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240917T024256Z
