// This template was generated by @sitecore-search/cli on Tue Jul 23 2024 14:56:02 GMT+0000 (Coordinated Universal Time)
import { CheckIcon } from '@radix-ui/react-icons';
import type {
  ActionProp,
  ItemClickedAction,
  SearchResponseFacet,
  SearchResponseFacetItem,
  SearchResponseSortChoice,
  SearchResultsInitialState,
  SearchResultsStoreState,
} from '@sitecore-search/react';
import {
  WidgetDataType,
  useSearchResults,
  useSearchResultsActions,
  useSearchResultsSelectedFilters,
  widget,
} from '@sitecore-search/react';
import {
  AccordionFacets,
  ArticleCard,
  FacetItem,
  Pagination,
  Presence,
  SearchResultsAccordionFacets,
  SortSelect,
} from '@sitecore-search/ui';
import { urlToFacet, useEnsureFacetUrl } from './use-ensure-facet-url';
import PreviewSearchListComponent from '../SearchPreview';
import { ChangeEvent, useEffect, useState } from 'react';
import { SvgIcon } from 'helpers/SvgIcon';

type ArticleCardItemCardProps = {
  className?: string;
  displayText?: boolean;
  article: ArticleModel;
  onItemClick: ActionProp<ItemClickedAction>;
  index: number;
};
type QueryResultsSummaryProps = {
  currentPage: number;
  itemsPerPage: number;
  totalItemsReturned: number;
  totalItems: number;
};
type SearchFacetsProps = {
  facets: SearchResponseFacet[];
};
type SearchPaginationProps = {
  currentPage: number;
  totalPages: number;
};
type SortOrderProps = {
  options: Array<SearchResponseSortChoice>;
  selected: string;
};
type SpinnerProps = {
  loading?: boolean;
};
interface RangeFacet {
  min?: number;
  max?: number;
  valueLabel?: string;
}
interface ValueFacet {
  valueLabel: string;
  min?: never;
  max?: never;
}
type SelectedFacet = RangeFacet | ValueFacet;

interface FacetPaginationItem {
  label: string;
  name: string;
  value: Array<SearchResponseFacetItem>;
  itemToLoad: number;
}
type FacepPagination = FacetPaginationItem;

const DEFAULT_IMG_URL = 'https://placehold.co/500x300?text=No%20Image'; // TODO: Update with corresponding fallback image
const buildRangeLabel = (min: number | undefined, max: number | undefined): string => {
  return typeof min === 'undefined'
    ? `< $${max}`
    : typeof max === 'undefined'
      ? ` > $${min}`
      : `$${min} - $${max}`;
};
const buildFacetLabel = (selectedFacet: SelectedFacet) => {
  if ('min' in selectedFacet || 'max' in selectedFacet) {
    return `${buildRangeLabel(selectedFacet.min, selectedFacet.max)}`;
  }
  return `${selectedFacet.valueLabel}`;
};

const ArticleHorizontalItemCard = ({
  className = '',
  article,
  displayText = false,
}: ArticleCardItemCardProps) => {
  return (
    <ArticleCard.Root
      key={article.id}
      className={`group flex flex-row flex-nowrap w-full relative gap-x-6 py-4 items-center ${className}`}
    >
      {/* CONTENT OF THE RESULT CARD */}
      <div className="w-[70%] space-y-2">
        <span className="text-[12px] font-normal">{article.eyebrow || 'Eyebrow'}</span>
        <ArticleCard.Title className="font-modern text-4xl font-bold line-clamp-1">
          {article.title || 'Headline'}
        </ArticleCard.Title>
        <ArticleCard.Subtitle className="mt-3 text-gray-500 text-[20px] font-normal line-clamp-1">
          {article.subtitle || 'Subhead'}
        </ArticleCard.Subtitle>
        {article.description && displayText && (
          <div className="line-clamp-3 text-sm">{article.description}</div>
        )}
        <div className="read-more flex items-center gap-2">
          <a className="underline text-base font-bold cursor-pointer" href={article.url}>
            Read more
          </a>
          <SvgIcon icon="arrow-right" viewBox="0 0 24 24" size="xs" fill="none" />
        </div>
      </div>
      {/* IMAGE OF THE RESULT CARD */}
      <div className="w-[30%] md:w-1/5 overflow-hidden  bg-gray-200">
        <ArticleCard.Image
          height={'100'}
          width={'100'}
          src={article?.image_url || DEFAULT_IMG_URL}
          className="w-full h-auto object-cover rounded-themes-radius-large-image-card"
        />
      </div>
    </ArticleCard.Root>
  );
};

const Filter = () => {
  const selectedFacetsFromApi = useSearchResultsSelectedFilters();
  const { onRemoveFilter, onClearFilters } = useSearchResultsActions();
  return selectedFacetsFromApi.length > 0 ? (
    <div>
      <div className="flex flex-col mb-2 gap-4">
        <div
          onClick={onClearFilters}
          className="clear-filter cursor-pointer flex gap-3 items-center text-base font-bold text-black underline text-opacity-75 hover:text-indigo-500 hover:opacity-1 focus:outline-indigo-500"
        >
          <span className="cursor-pointer">Reset Filters</span>
          <SvgIcon size="xs" icon="close" viewBox="0 0 16 10 " />
        </div>
      </div>
      <div className="flex flex-wrap">
        {selectedFacetsFromApi.map((selectedFacet) => (
          <button
            key={`${selectedFacet.facetId}${selectedFacet.facetLabel}${selectedFacet.valueLabel}`}
            onClick={() => onRemoveFilter(selectedFacet)}
            className="text-ellipsis text-sm text-white bg-gray-400 rounded-lg pl-2.5 pr-7 py-2.5 whitespace-no-wrap max-w-full overflow-hidden relative cursor-pointer 
      before:content-[''] before:-rotate-45 before:absolute before:w-3.5 before:h-0.5 before:right-2 before:top-2/4 before:bg-white 
      after:content-[''] after:rotate-45 after:absolute after:w-3.5 after:h-0.5 after:right-2 after:top-2/4 after:bg-white 
      focus:outline-indigo-500"
          >
            {buildFacetLabel(selectedFacet)}
          </button>
        ))}
      </div>
    </div>
  ) : (
    <></>
  );
};

const QueryResultsSummary = ({ totalItems }: QueryResultsSummaryProps) => {
  return (
    <div className="keyword flex flex-col gap-4">
      <p className="text-base">Your search for KEYWORD returned {totalItems} results</p>
      <hr />
    </div>
  );
};

// const ResultsPerPage = ({ defaultItemsPerPage }: ResultsPerPageProps) => {
//   const { onResultsPerPageChange } = useSearchResultsActions();
//   return (
//     <div>
//       <label className="pr-1">Results Per Page</label>
//       <Select.Root
//         defaultValue={String(defaultItemsPerPage)}
//         onValueChange={(v) =>
//           onResultsPerPageChange({
//             numItems: Number(v),
//           })
//         }
//       >
//         <Select.Trigger className="cursor-pointer inline-flex items-center bg-transparent h-10 gap-1 py-1 px-4 border-0 focus:outline-indigo-500">
//           <Select.SelectValue />
//           <Select.Icon />
//         </Select.Trigger>
//         <Select.SelectContent className="bg-white shadow-[2px_2px_4px_#CFCFCF] z-[100]">
//           <Select.Viewport className="p-1">
//             <Select.SelectItem
//               value="24"
//               className="flex items-center leading-none cursor-pointer select-none whitespace-no-wrap h-6 px-1 hover:bg-indigo-500 hover:text-white data-[state=checked]:text-indigo-500 data-[state=checked]:bg-white focus:outline-indigo-500"
//             >
//               <SortSelect.OptionText>24</SortSelect.OptionText>
//             </Select.SelectItem>

//             <Select.SelectItem
//               value="48"
//               className="flex items-center leading-none cursor-pointer select-none whitespace-no-wrap h-6 px-1 hover:bg-indigo-500 hover:text-white data-[state=checked]:text-indigo-500 data-[state=checked]:bg-white focus:outline-indigo-500"
//             >
//               <SortSelect.OptionText>48</SortSelect.OptionText>
//             </Select.SelectItem>

//             <Select.SelectItem
//               value="64"
//               className="flex items-center leading-none cursor-pointer select-none whitespace-no-wrap h-6 px-1 hover:bg-indigo-500 hover:text-white data-[state=checked]:text-indigo-500 data-[state=checked]:bg-white focus:outline-indigo-500"
//             >
//               <SortSelect.OptionText>64</SortSelect.OptionText>
//             </Select.SelectItem>
//           </Select.Viewport>
//         </Select.SelectContent>
//       </Select.Root>
//     </div>
//   );
// };

const SearchFacets = ({ facets }: SearchFacetsProps) => {
  const ITEM_TO_LOAD = 5;

  const { onFacetClick } = useSearchResultsActions();

  const [facetsPagination, setFacetsPagination] = useState<FacepPagination[] | undefined>(
    undefined
  );

  useEffect(() => {
    const facetsPagination: FacepPagination[] = [];
    facets.map((f) => {
      const obj = {
        name: f.name,
        value: f.value,
        label: f.label,
        itemToLoad: ITEM_TO_LOAD,
      };
      facetsPagination.push(obj);
    });
    setFacetsPagination(facetsPagination);
  }, [facets]);

  const onShowMore = (index: number) => {
    setFacetsPagination((prevFacetsPagination) => {
      if (!prevFacetsPagination) return [];

      const newFacetsPagination = [...prevFacetsPagination];
      const item = { ...newFacetsPagination[index] };
      item.itemToLoad = ITEM_TO_LOAD + item.itemToLoad;
      newFacetsPagination[index] = item;

      return newFacetsPagination;
    });
  };

  const onFacetSearch = (e: ChangeEvent<HTMLInputElement>, index: number) => {
    const facetSearchText = e.target.value;
    if (facetSearchText) {
      setFacetsPagination((prevFacetsPagination) => {
        if (!prevFacetsPagination) return [];

        const newFacetsPagination = [...prevFacetsPagination];
        const item = { ...newFacetsPagination[index] };
        const filteredItems = item.value.filter((x) => {
          return x.text.toLocaleLowerCase().match(facetSearchText.toLocaleLowerCase());
        });
        item.value = filteredItems;
        newFacetsPagination[index] = item;

        return newFacetsPagination;
      });
    } else {
      const facetsPagination: FacepPagination[] = [];
      facets.map((f) => {
        const obj = {
          name: f.name,
          value: f.value,
          label: f.label,
          itemToLoad: ITEM_TO_LOAD,
        };
        facetsPagination.push(obj);
      });
      setFacetsPagination(facetsPagination);
    }
  };

  return (
    <SearchResultsAccordionFacets
      id="facets"
      defaultFacetTypesExpandedList={[]}
      onFacetValueClick={onFacetClick}
    >
      {facetsPagination &&
        facetsPagination.map((f, fIndex: number) => (
          // ALL THE CONTENT IN THE FILTER OPTION
          <AccordionFacets.Facet
            facetId={f.name}
            key={fIndex}
            id={f.name + fIndex}
            className="mb-2 border-x border-y w-full gap-2 rounded-md"
          >
            <div className="facets-header">
              <AccordionFacets.Header className="flex px-3 py-1.5">
                {/* FILTER ITEM TITLE */}
                <AccordionFacets.Trigger className="flex items-center justify-between w-full text-base">
                  {f.label}
                  {/* DROPDOWN/UP ICON */}
                  <SvgIcon
                    className="facets-accordian-arrow"
                    viewBox="0 0 24 24"
                    size="xs"
                    icon="chevron-up"
                    fill="none"
                  />
                </AccordionFacets.Trigger>
              </AccordionFacets.Header>
            </div>
            {/* INSIDE OF EACH INDIVIDUAL FILTER ITEM */}
            <AccordionFacets.Content>
              <AccordionFacets.ValueList className="list-none flex flex-col justify-start space-y-4 px-3 mt-2 mb-3">
                {/* INDIVIDUAL SEARCH BOX */}
                <div className="search-textbox relative w-full">
                  <input
                    type="text"
                    onChange={(e) => onFacetSearch(e, fIndex)}
                    placeholder="Search"
                    className="w-full rounded border px-2 h-[48px] border-black"
                  />
                  <div className="magnifier-icon absolute top-1/2 right-2 transform -translate-y-1/2">
                    <SvgIcon icon="magnifier" size="xs" viewBox="0 0 18 18" fill="none" />
                  </div>
                </div>
                {/* INDIVIDUAL CHECKBOX + LABEL + COUNT */}
                {f.value.slice(0, f.itemToLoad).map((v, index: number) => (
                  <FacetItem
                    {...{
                      index,
                      facetValueId: v.id,
                    }}
                    key={index}
                    className="group flex cursor-pointer w-full items-center justify-between text-base"
                  >
                    {/* ACTUAL check+label */}
                    <div className="facetlabel justify-start w-11/12 items-center flex gap-2">
                      <AccordionFacets.ItemCheckbox className="form-checkbox flex-none w-5 h-5 border border-gray-300 rounded cursor-pointer transition duration-500 ease-in-out hover:border-heading aria-checked:ring-1 aria-checked:ring-black aria-checked:focus aria-checked:hover:bg-heading aria-checked:focus:bg-heading">
                        <AccordionFacets.ItemCheckboxIndicator>
                          <CheckIcon className="w-full h-full" />
                        </AccordionFacets.ItemCheckboxIndicator>
                      </AccordionFacets.ItemCheckbox>
                      <AccordionFacets.ItemLabel className="text-base">
                        {v.text}
                      </AccordionFacets.ItemLabel>
                    </div>
                    {/* COUNT */}
                    <div className="facetcount pr-1">{v.count && `(${v.count})`}</div>
                  </FacetItem>
                ))}
                {/* INDIVIDUAL SHOW MORE BUTTON */}
                {!(f.value.length > f.itemToLoad) ||
                  (f.value.length > ITEM_TO_LOAD && (
                    <div
                      onClick={() => {
                        onShowMore(fIndex);
                      }}
                      className="cursor-pointer show-more-facets flex gap-2 items-center w-11/12 font-semibold text-base p-1"
                    >
                      <SvgIcon icon="plus" fill="none" viewBox="0 0 12 11" size="xxs" />
                      <h2 className="underline text-sm">Show more</h2>
                    </div>
                  ))}
              </AccordionFacets.ValueList>
            </AccordionFacets.Content>
          </AccordionFacets.Facet>
        ))}
    </SearchResultsAccordionFacets>
  );
};

// PAGINATION CODE IN THE BOTTOM OF THE RESULTS
const SearchPagination = ({ currentPage, totalPages }: SearchPaginationProps) => {
  const { onPageNumberChange } = useSearchResultsActions();
  return (
    <Pagination.Root
      currentPage={currentPage}
      defaultCurrentPage={1}
      totalPages={totalPages}
      onPageChange={(v) =>
        onPageNumberChange({
          page: v,
        })
      }
      className="flex gap-4 text-base"
    >
      <Pagination.PrevPage
        onClick={(e) => e.preventDefault()}
        className="flex items-center cursor-pointer my-0 mx-2 data-[current=true]:hidden hover:text-indigo-500 focus:outline-indigo-500"
      >
        <SvgIcon icon="arrow-left" size="xs" viewBox="0 0 24 24" fill="none" />
      </Pagination.PrevPage>
      <Pagination.Pages>
        {(pagination) =>
          Pagination.paginationLayout(pagination, {
            boundaryCount: 1,
            siblingCount: 1,
          }).map(({ page, type }) =>
            type === 'page' ? (
              <Pagination.Page
                key={page}
                aria-label={`Page ${page}`}
                page={page as number}
                onClick={(e) => e.preventDefault()}
                className="inline-flex mx-2 items-center justify-center w-8 h-8 rounded-full p-2 cursor-pointer data-[current=true]:text-white data-[current=true]:bg-gray-500 data-[current=true]:pointer-events-none data-[current=true]:no-underline"
              >
                {page}
              </Pagination.Page>
            ) : (
              <span key={type}>...</span>
            )
          )
        }
      </Pagination.Pages>
      <Pagination.NextPage
        onClick={(e) => e.preventDefault()}
        className="flex items-center justify-center cursor-pointer my-0 mx-2 data-[current=true]:hidden hover:text-indigo-500 focus:outline-indigo-500"
      >
        <SvgIcon icon="arrow-right" size="xs" viewBox="0 0 24 24" fill="none" />
        {/* <svg
          width="9"
          height="16"
          viewBox="0 0 9 16"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M0.999999 1L8 8L1 15"
            stroke="#2F2D2E"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg> */}
      </Pagination.NextPage>
    </Pagination.Root>
  );
};

const SortOrder = ({ options, selected }: SortOrderProps) => {
  const selectedSortIndex = options.findIndex((s) => s.name === selected);
  const { onSortChange } = useSearchResultsActions();
  return (
    <SortSelect.Root defaultValue={options[selectedSortIndex]?.name} onValueChange={onSortChange}>
      <SortSelect.Trigger className="cursor-pointer flex items-center bg-transparent h-10 gap-1 focus:outline-indigo-500 justify-between w-full">
        <SortSelect.SelectValue>
          {selectedSortIndex > -1 ? options[selectedSortIndex].label : ''}
        </SortSelect.SelectValue>
        {/* <SortSelect.Icon /> */}
        <SvgIcon icon="sorting" viewBox="0 0 24 24" size="xs" />
      </SortSelect.Trigger>
      <SortSelect.Content className="bg-white shadow-[4px_4px_8px_#CFCFCF] z-[100] absolute top-6 focus-within:border-indigo-500 w-full ">
        <SortSelect.Viewport className="p-1 z-[50000]">
          {options.map((option: SearchResponseSortChoice) => (
            <SortSelect.Option
              value={option}
              key={option.name}
              className="flex items-center leading-none cursor-pointer select-none whitespace-no-wrap h-10 px-1 hover:bg-indigo-500 hover:text-white data-[state=checked]:text-indigo-500 data-[state=checked]:bg-white focus:outline-indigo-500"
            >
              <SortSelect.OptionText>{option.label}</SortSelect.OptionText>
            </SortSelect.Option>
          ))}
        </SortSelect.Viewport>
      </SortSelect.Content>
    </SortSelect.Root>
  );
};

const Spinner = ({ loading = false }: SpinnerProps) => {
  return (
    <Presence present={loading}>
      <div className="text-center">
        <div role="status">
          <svg
            aria-busy={loading}
            aria-hidden={!loading}
            focusable="false"
            role="progressbar"
            viewBox="0 0 20 20"
            className="inline animate-spin w-10 text-slate-900"
          >
            <path d="M7.229 1.173a9.25 9.25 0 1 0 11.655 11.412 1.25 1.25 0 1 0-2.4-.698 6.75 6.75 0 1 1-8.506-8.329 1.25 1.25 0 1 0-.75-2.385z" />
          </svg>
          <span className="sr-only">Loading...</span>
        </div>
      </div>
    </Presence>
  );
};

type ArticleModel = {
  id: string;
  type?: string;
  title?: string;
  name?: string;
  subtitle?: string;
  url?: string;
  description?: string;
  content_text?: string;
  image_url?: string;
  source_id?: string;
  eyebrow?: string;
};

type ArticleSearchResultsProps = {
  defaultSortType?: SearchResultsStoreState['sortType'];
  defaultPage?: SearchResultsStoreState['page'];
  defaultItemsPerPage?: SearchResultsStoreState['itemsPerPage'];
  defaultKeyphrase?: SearchResultsStoreState['keyphrase'];
};

type InitialState = SearchResultsInitialState<'itemsPerPage' | 'keyphrase' | 'page' | 'sortType'>;

export const SearchResultsWithInputComponent = ({
  defaultSortType = 'featured_desc',
  defaultPage = 1,
  defaultKeyphrase = '',
  defaultItemsPerPage = 24,
}: ArticleSearchResultsProps) => {
  const [mobileFilterToogle, setMobileFilterToogle] = useState<boolean>(false);

  // const [searchText, setSearchText] = useState<string>('');
  // const [commitedSearchText, setCommitedSearchText] = useState<string>('');
  // const searchParam = useSearchParams();

  // useEffect(() => {
  //   const searchString: string | null = searchParam.get('q') || '';
  //   setCommitedSearchText(searchString);
  //   setSearchText(searchString);
  // }, []);

  const searchResults = useSearchResults<ArticleModel, InitialState>({
    config: {
      defaultFacetType: 'text',
    },
    state: () => {
      const hasWindow = typeof window !== 'undefined';
      const hash = hasWindow ? window.location.hash.replace('#', '') : '';
      const facetsFromUrl = urlToFacet(hash);
      const defaultSearchText = hasWindow && window.location.search.replace('=', ' ').split(' ')[1];

      return {
        sortType: defaultSortType,
        page: defaultPage,
        itemsPerPage: defaultItemsPerPage,
        keyphrase: defaultSearchText || defaultKeyphrase,
        selectedFacets: facetsFromUrl,
      };
    },
  });

  const {
    widgetRef,
    actions,
    state,
    queryResult: { isLoading, isFetching, data },
  } = searchResults;

  const {
    total_item: totalItems = 0,
    sort: { choices: sortChoices = [] } = {},
    facet: facets = [],
    content: articles = [],
  } = data ?? {};

  const { itemsPerPage, sortType, page } = state;

  const { onItemClick } = actions;

  // Ensure that facets are synced with url
  useEnsureFacetUrl(actions, facets);

  const totalPages = Math.ceil(totalItems / itemsPerPage);

  // const onHandle = (e: FormEvent<HTMLFormElement>) => {
  //   e.preventDefault();
  //   setCommitedSearchText(searchText);
  //   onKeyphraseChange({
  //     keyphrase: searchText,
  //   });
  // };

  // const keyphraseChangeFn = (e: ChangeEvent<HTMLInputElement>) => {
  //   const searchText = e.target.value;
  //   setSearchText(searchText);
  // };

  if (isLoading) {
    return (
      <div className="flex justify-center items-center h-screen w-full bg-white">
        <Spinner loading />
      </div>
    );
  }

  return (
    <div ref={widgetRef}>
      <div className="flex flex-col lg:flex-row relative max-w-full px-4 text-black text-opacity-75 gap-4">
        {/* LOADING STATE */}
        {isFetching && (
          <div className="w-full h-full fixed top-0 left-0 bottom-0 right-0 z-30 bg-white opacity-50">
            <div className="absolute top-[50%] left-[50%] -translate-x-[50%] -translate-y-[50%] flex flex-col justify-center items-center z-40">
              <Spinner loading />
            </div>
          </div>
        )}
        {totalItems > 0 && (
          <>
            <section
              className={`flex-col flex-none relative md:gap-4 gap-4 mr-8 w-full mmd:w-[40%] lg:w-[25%] font-modern`}
            >
              <div className="relative block w-full my-4">
                {/* <form id="searchSubmit" onSubmit={onHandle}>
                  <input
                    onChange={(e) => keyphraseChangeFn(e)}
                    className="peer border rounded w-full p-2 pr-[25px] focus:outline-indigo-500"
                    value={searchText}
                  />
                </form>
                <MagnifyingGlassIcon className="absolute right-[5px] top-[10px] w-[20px] h-[20px] text-gray-400 peer-focus:text-indigo-500" /> */}

                {/* SEARCH BAR - SAME FOR BOTH MOBILE AND DESKTOP */}
                <PreviewSearchListComponent
                  rfkId={'rfkid_101'}
                  defaultItemsPerPage={5}
                  hasSearchFromSearchPage={true}
                />
              </div>
              {/* REFINE BY CODE */}
              <div
                onClick={() => {
                  setMobileFilterToogle(!mobileFilterToogle);
                }}
                className={`lg:hidden flex items-center justify-center w-full border rounded px-2 h-12 gap-2 mt-2`}
              >
                {/* THIS IS FOR REFINE BY MOBILE */}
                <span className="text-lg font-semibold mt-2">Refine By</span>
                <SvgIcon icon="refine" viewBox="0 0 24 24" size="xs" fill="none" />
              </div>
              <div
                className={`refineby-container ${mobileFilterToogle ? 'block' : 'hidden'} lg:block`}
              >
                {/* THIS IS FOR REFINE BY DESKTOP */}
                <div className="sort-order flex flex-col gap-3">
                  <h3 className="text-lg font-semibold mt-2">Refine By</h3>
                  {/* SORT BY CODE */}
                  <div className="sort gap-1">
                    <label className="text-base font-bold mb-1" htmlFor="sorting">
                      Sort
                    </label>
                    <div
                      id="sorting"
                      className="sort-wrapper border-x border-y border-slate-500 rounded px-2"
                    >
                      <SortOrder options={sortChoices} selected={sortType} />
                    </div>
                  </div>
                </div>
                {/* FILTER CODE */}
                <div className="my-4">
                  <Filter />
                </div>
                {/* FILTER CONTENT */}
                {facets.length > 0 && (
                  <div className="search-facets">
                    <label htmlFor="facets" className="text-base font-bold mb-1">
                      Filter
                    </label>
                    <SearchFacets facets={facets} />
                  </div>
                )}
              </div>
            </section>
            {/* RIGHT SIDE SECTION WHICH DISPLAYS RESULTS ON DESKTOP */}
            <section className="flex flex-col flex-[4_1_0%] gap-4 font-modern md:p-4">
              {/* Sort Select */}
              {totalItems > 0 && (
                <QueryResultsSummary
                  currentPage={page}
                  itemsPerPage={itemsPerPage}
                  totalItems={totalItems}
                  totalItemsReturned={articles.length}
                />
              )}
              <section className="flex justify-between text-xs">
                {/* <SortOrder options={sortChoices} selected={sortType} /> */}
              </section>

              {/* Results */}
              <div className="w-full gap-x-6">
                {articles.map((a, index) => (
                  <>
                    <ArticleHorizontalItemCard
                      key={a.id}
                      article={a as ArticleModel}
                      index={index}
                      onItemClick={onItemClick}
                      displayText={true}
                    />
                  </>
                ))}
              </div>
              <div className="flex flex-col md:flex-row text-xs w-full justify-center items-center">
                {/* <ResultsPerPage defaultItemsPerPage={defaultItemsPerPage} /> */}
                <SearchPagination currentPage={page} totalPages={totalPages} />
              </div>
            </section>
          </>
        )}
        {totalItems <= 0 && !isFetching && (
          <>
            <section className="flex flex-col flex-none relative gap-4 mr-8 w-full md:w-[25%] font-modern">
              <div className="relative block w-full">
                {/* <form id="searchSubmit" onSubmit={onHandle}>
                  <input
                    onChange={(e) => keyphraseChangeFn(e)}
                    className="peer border rounded w-full p-2 pr-[25px] focus:outline-indigo-500"
                    value={searchText}
                  />
                </form>
                <MagnifyingGlassIcon className="absolute right-[5px] top-[10px] w-[20px] h-[20px] text-gray-400 peer-focus:text-indigo-500" /> */}
              </div>
            </section>
            <div className="w-full flex justify-center">
              <h3>0 Results</h3>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

const SearchResultsWithInputWidget = widget(
  SearchResultsWithInputComponent,
  WidgetDataType.SEARCH_RESULTS,
  'content'
);

export default SearchResultsWithInputWidget;
