---
ID: "ddd80eb2-33d3-45dc-80df-922dd097133d"
Parent: "c3ed0731-9d2b-4ec8-9494-760921cadd37"
Template: "c3ed0731-9d2b-4ec8-9494-760921cadd37"
Path: /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Card/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d7e274e3-be94-47ca-9cb9-9a44772efb22"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\pbarron@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240311T154432Z
