---
ID: "bf890d5f-61e6-446f-be54-a53abf538007"
Parent: "e49ce774-5c1d-4727-9796-a256da64893a"
Template: "e49ce774-5c1d-4727-9796-a256da64893a"
Path: /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/Hero/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1d7eb7c6-3cf5-424a-8fc3-2d456b7ac0bc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mchaniyara@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240515T113847Z
