---
ID: "2146ddda-8d5d-48be-a413-62ada979b739"
Parent: "0ce03778-0d61-4fb0-a95e-61e7236201ed"
Template: "0ce03778-0d61-4fb0-a95e-61e7236201ed"
Path: /sitecore/templates/Feature/HztlFoundation/HztlPageContent/Rendering Parameters/RTE/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "41cf50ab-76e0-436a-85e2-7fbb62b1f46b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\asavalagi@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240614T120313Z
